### ISSUE TITLE
Hide jumbotron slogan for narrow (maybe <=600px) viewports

### ISSUE THREAD

**Issue by ausbin** [uniting-humanitarians/uh#74]
When the viewport is narrower than 600px, hide the jumbotron slogan thing (semi-transparent black box in screenshot below). Because it overlaps the page title on (for example) a 400x700px viewport:

![screen shot 2017-09-10 at 13 43 35](https://user-images.githubusercontent.com/431756/30251495-29a60122-962e-11e7-887e-e50a17775978.png)

As far as I understand, the only file you should need to change is `/ghu_web/ghu_main/base.css` to fix this.

**Comment by ausbin** [comment]
@media (max-width: 600px ) {
        .jumbotron p {
            display: none;
        }
    }

**Comment by S-reinken** [comment]
Due Monday 9/18
